import LocalizedStrings from 'react-localization'

export const strings = new LocalizedStrings({
  en: {
    backHome: 'Back Homepage',
    settings: 'Settings',
    caInstalled: 'ApiTune CA Certificate Installed',
    caNotTrust: 'ApiTune CA Certificate Not Trusted',
    trustCa: 'Trust ApiTune CA',
    requireRoot: 'Require root privileges',
    exportCa: 'Export CA File',
    update: 'Update',
    ca: 'CA',
    proxyPort: 'Proxy Port',
    themes: 'Themes',
    language: 'Language',
    apiRules: 'API Rules',
    network: 'Network',
    test: 'Test',
    addRuleToCreateTest: 'Add rule to create a test',
    testAll: 'All',
    testFailed: 'Failed',
    testPassed: 'Passed',
    testResults: 'Test Results',
    reqDetails: 'Request Details'
  },
  zh: {
    backHome: '返回首页',
    settings: '设置',
    caInstalled: 'ApiTune CA 证书已安装',
    caNotTrust: 'ApiTune CA 证书未受信任',
    trustCa: '信任 ApiTune CA',
    requireRoot: '需要 root 权限',
    exportCa: '导出 CA 文件',
    update: '更新',
    ca: '证书',
    proxyPort: '代理端口',
    themes: '主题',
    language: '语言',
    apiRules: 'API 规则',
    network: '网络',
    test: '测试',
    addRuleToCreateTest: '添加规则以创建测试用例',
    testAll: '全部用例',
    testFailed: '失败用例',
    testPassed: '通过用例',
    testResults: '测试结果',
    reqDetails: '请求详情'
  }
})
